spring:
  jpa:
    hibernate:
      ddl-auto: none #create update none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k9a203.p.ssafy.io:3306/showeat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: showeat
    password: showeat1357
  #redis
  data:
    redis:
      host: k9a203.p.ssafy.io
      port: 6379
  #security
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://showeat.kr/sign-in/loading

# TossPayments
payments:
  toss:
    test_client_api_key: test_ck_QbgMGZzorzyKv2BGY6djVl5E1em4
    test_secret_api_key: test_sk_Ba5PzR0ArnWLjDw7vPe18vmYnNeD
    success_url: https://showeat.kr/api/payments/request/success
    fail_url: https://showeat.kr/api/payments/request/fail

kafka:
  server: "k9a203.p.ssafy.io:9092"